### ISSUE TITLE
Driver [KarixChannel::class] not supported.

### ISSUE THREAD

**Issue by stemword** [s-sarthak/Laravel-Notification-Channel-KarixSms#4]
Hello  I Install  bitfumes/karix-notification-channel via composer
 and also add

use Bitfumes\KarixNotificationChannel\KarixChannel;
use Bitfumes\KarixNotificationChannel\KarixMessage;
 in my notification file  .
But while running code I am getting Driver [KarixChannel::class] not supported issue.I  am using laravel 5.6

**Comment by edwinsmasher** [comment]
Is your App name Bitfumes? use your Appname .ie
use YourAppName\KarixNotificationChannel\KarixChannel;
